/*
 * Postmark Account-level API
 * Postmark makes sending and receiving email  incredibly easy. The Account-level API allows users to configure all Servers, Domains, and Sender Signatures associated  with an Account. 
 *
 * OpenAPI spec version: 0.9.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package net.nextpulse.postmarkapp.models.account;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * 
 */
@ApiModel(description = "")
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2017-02-24T16:43:30.269+01:00")
public class CreateServerPayload {
  @JsonProperty("Name")
  private String name = null;

  @JsonProperty("Color")
  private String color = null;

  @JsonProperty("RawEmailEnabled")
  private Boolean rawEmailEnabled = null;

  @JsonProperty("DeliveryHookUrl")
  private String deliveryHookUrl = null;

  @JsonProperty("SmtpApiActivated")
  private Boolean smtpApiActivated = null;

  @JsonProperty("InboundHookUrl")
  private String inboundHookUrl = null;

  @JsonProperty("BounceHookUrl")
  private String bounceHookUrl = null;

  @JsonProperty("OpenHookUrl")
  private String openHookUrl = null;

  @JsonProperty("PostFirstOpenOnly")
  private Boolean postFirstOpenOnly = null;

  @JsonProperty("TrackOpens")
  private Boolean trackOpens = null;

  @JsonProperty("InboundDomain")
  private String inboundDomain = null;

  @JsonProperty("InboundSpamThreshold")
  private Integer inboundSpamThreshold = null;

  public CreateServerPayload name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public CreateServerPayload color(String color) {
    this.color = color;
    return this;
  }

   /**
   * Get color
   * @return color
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getColor() {
    return color;
  }

  public void setColor(String color) {
    this.color = color;
  }

  public CreateServerPayload rawEmailEnabled(Boolean rawEmailEnabled) {
    this.rawEmailEnabled = rawEmailEnabled;
    return this;
  }

   /**
   * Get rawEmailEnabled
   * @return rawEmailEnabled
  **/
  @ApiModelProperty(example = "null", value = "")
  public Boolean getRawEmailEnabled() {
    return rawEmailEnabled;
  }

  public void setRawEmailEnabled(Boolean rawEmailEnabled) {
    this.rawEmailEnabled = rawEmailEnabled;
  }

  public CreateServerPayload deliveryHookUrl(String deliveryHookUrl) {
    this.deliveryHookUrl = deliveryHookUrl;
    return this;
  }

   /**
   * Get deliveryHookUrl
   * @return deliveryHookUrl
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getDeliveryHookUrl() {
    return deliveryHookUrl;
  }

  public void setDeliveryHookUrl(String deliveryHookUrl) {
    this.deliveryHookUrl = deliveryHookUrl;
  }

  public CreateServerPayload smtpApiActivated(Boolean smtpApiActivated) {
    this.smtpApiActivated = smtpApiActivated;
    return this;
  }

   /**
   * Get smtpApiActivated
   * @return smtpApiActivated
  **/
  @ApiModelProperty(example = "null", value = "")
  public Boolean getSmtpApiActivated() {
    return smtpApiActivated;
  }

  public void setSmtpApiActivated(Boolean smtpApiActivated) {
    this.smtpApiActivated = smtpApiActivated;
  }

  public CreateServerPayload inboundHookUrl(String inboundHookUrl) {
    this.inboundHookUrl = inboundHookUrl;
    return this;
  }

   /**
   * Get inboundHookUrl
   * @return inboundHookUrl
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getInboundHookUrl() {
    return inboundHookUrl;
  }

  public void setInboundHookUrl(String inboundHookUrl) {
    this.inboundHookUrl = inboundHookUrl;
  }

  public CreateServerPayload bounceHookUrl(String bounceHookUrl) {
    this.bounceHookUrl = bounceHookUrl;
    return this;
  }

   /**
   * Get bounceHookUrl
   * @return bounceHookUrl
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getBounceHookUrl() {
    return bounceHookUrl;
  }

  public void setBounceHookUrl(String bounceHookUrl) {
    this.bounceHookUrl = bounceHookUrl;
  }

  public CreateServerPayload openHookUrl(String openHookUrl) {
    this.openHookUrl = openHookUrl;
    return this;
  }

   /**
   * Get openHookUrl
   * @return openHookUrl
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getOpenHookUrl() {
    return openHookUrl;
  }

  public void setOpenHookUrl(String openHookUrl) {
    this.openHookUrl = openHookUrl;
  }

  public CreateServerPayload postFirstOpenOnly(Boolean postFirstOpenOnly) {
    this.postFirstOpenOnly = postFirstOpenOnly;
    return this;
  }

   /**
   * Get postFirstOpenOnly
   * @return postFirstOpenOnly
  **/
  @ApiModelProperty(example = "null", value = "")
  public Boolean getPostFirstOpenOnly() {
    return postFirstOpenOnly;
  }

  public void setPostFirstOpenOnly(Boolean postFirstOpenOnly) {
    this.postFirstOpenOnly = postFirstOpenOnly;
  }

  public CreateServerPayload trackOpens(Boolean trackOpens) {
    this.trackOpens = trackOpens;
    return this;
  }

   /**
   * Get trackOpens
   * @return trackOpens
  **/
  @ApiModelProperty(example = "null", value = "")
  public Boolean getTrackOpens() {
    return trackOpens;
  }

  public void setTrackOpens(Boolean trackOpens) {
    this.trackOpens = trackOpens;
  }

  public CreateServerPayload inboundDomain(String inboundDomain) {
    this.inboundDomain = inboundDomain;
    return this;
  }

   /**
   * Get inboundDomain
   * @return inboundDomain
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getInboundDomain() {
    return inboundDomain;
  }

  public void setInboundDomain(String inboundDomain) {
    this.inboundDomain = inboundDomain;
  }

  public CreateServerPayload inboundSpamThreshold(Integer inboundSpamThreshold) {
    this.inboundSpamThreshold = inboundSpamThreshold;
    return this;
  }

   /**
   * Get inboundSpamThreshold
   * @return inboundSpamThreshold
  **/
  @ApiModelProperty(example = "null", value = "")
  public Integer getInboundSpamThreshold() {
    return inboundSpamThreshold;
  }

  public void setInboundSpamThreshold(Integer inboundSpamThreshold) {
    this.inboundSpamThreshold = inboundSpamThreshold;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CreateServerPayload createServerPayload = (CreateServerPayload) o;
    return Objects.equals(this.name, createServerPayload.name) &&
        Objects.equals(this.color, createServerPayload.color) &&
        Objects.equals(this.rawEmailEnabled, createServerPayload.rawEmailEnabled) &&
        Objects.equals(this.deliveryHookUrl, createServerPayload.deliveryHookUrl) &&
        Objects.equals(this.smtpApiActivated, createServerPayload.smtpApiActivated) &&
        Objects.equals(this.inboundHookUrl, createServerPayload.inboundHookUrl) &&
        Objects.equals(this.bounceHookUrl, createServerPayload.bounceHookUrl) &&
        Objects.equals(this.openHookUrl, createServerPayload.openHookUrl) &&
        Objects.equals(this.postFirstOpenOnly, createServerPayload.postFirstOpenOnly) &&
        Objects.equals(this.trackOpens, createServerPayload.trackOpens) &&
        Objects.equals(this.inboundDomain, createServerPayload.inboundDomain) &&
        Objects.equals(this.inboundSpamThreshold, createServerPayload.inboundSpamThreshold);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, color, rawEmailEnabled, deliveryHookUrl, smtpApiActivated, inboundHookUrl, bounceHookUrl, openHookUrl, postFirstOpenOnly, trackOpens, inboundDomain, inboundSpamThreshold);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CreateServerPayload {\n");
    
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    color: ").append(toIndentedString(color)).append("\n");
    sb.append("    rawEmailEnabled: ").append(toIndentedString(rawEmailEnabled)).append("\n");
    sb.append("    deliveryHookUrl: ").append(toIndentedString(deliveryHookUrl)).append("\n");
    sb.append("    smtpApiActivated: ").append(toIndentedString(smtpApiActivated)).append("\n");
    sb.append("    inboundHookUrl: ").append(toIndentedString(inboundHookUrl)).append("\n");
    sb.append("    bounceHookUrl: ").append(toIndentedString(bounceHookUrl)).append("\n");
    sb.append("    openHookUrl: ").append(toIndentedString(openHookUrl)).append("\n");
    sb.append("    postFirstOpenOnly: ").append(toIndentedString(postFirstOpenOnly)).append("\n");
    sb.append("    trackOpens: ").append(toIndentedString(trackOpens)).append("\n");
    sb.append("    inboundDomain: ").append(toIndentedString(inboundDomain)).append("\n");
    sb.append("    inboundSpamThreshold: ").append(toIndentedString(inboundSpamThreshold)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

