/*
 * Postmark Account-level API
 * Postmark makes sending and receiving email  incredibly easy. The Account-level API allows users to configure all Servers, Domains, and Sender Signatures associated  with an Account. 
 *
 * OpenAPI spec version: 0.9.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package net.nextpulse.postmarkapp.models.account;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * 
 */
@ApiModel(description = "")
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2017-02-24T16:43:30.269+01:00")
public class DKIMRotationResponse {
  @JsonProperty("Name")
  private String name = null;

  @JsonProperty("DKIMVerified")
  private Boolean dKIMVerified = null;

  @JsonProperty("WeakDKIM")
  private Boolean weakDKIM = null;

  @JsonProperty("DKIMHost")
  private String dKIMHost = null;

  @JsonProperty("DKIMTestValue")
  private String dKIMTestValue = null;

  @JsonProperty("DKIMPendingHost")
  private String dKIMPendingHost = null;

  @JsonProperty("DKIMPendingTextValue")
  private String dKIMPendingTextValue = null;

  @JsonProperty("DKIMRevokedHost")
  private String dKIMRevokedHost = null;

  @JsonProperty("DKIMRevokedTextValue")
  private String dKIMRevokedTextValue = null;

  @JsonProperty("SafeToRemoveRevokedKeyFromDNS")
  private Boolean safeToRemoveRevokedKeyFromDNS = null;

  @JsonProperty("DKIMUpdateStatus")
  private String dKIMUpdateStatus = null;

  @JsonProperty("ID")
  private Long ID = null;

  public DKIMRotationResponse name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public DKIMRotationResponse dKIMVerified(Boolean dKIMVerified) {
    this.dKIMVerified = dKIMVerified;
    return this;
  }

   /**
   * Get dKIMVerified
   * @return dKIMVerified
  **/
  @ApiModelProperty(example = "null", value = "")
  public Boolean getDKIMVerified() {
    return dKIMVerified;
  }

  public void setDKIMVerified(Boolean dKIMVerified) {
    this.dKIMVerified = dKIMVerified;
  }

  public DKIMRotationResponse weakDKIM(Boolean weakDKIM) {
    this.weakDKIM = weakDKIM;
    return this;
  }

   /**
   * Get weakDKIM
   * @return weakDKIM
  **/
  @ApiModelProperty(example = "null", value = "")
  public Boolean getWeakDKIM() {
    return weakDKIM;
  }

  public void setWeakDKIM(Boolean weakDKIM) {
    this.weakDKIM = weakDKIM;
  }

  public DKIMRotationResponse dKIMHost(String dKIMHost) {
    this.dKIMHost = dKIMHost;
    return this;
  }

   /**
   * Get dKIMHost
   * @return dKIMHost
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getDKIMHost() {
    return dKIMHost;
  }

  public void setDKIMHost(String dKIMHost) {
    this.dKIMHost = dKIMHost;
  }

  public DKIMRotationResponse dKIMTestValue(String dKIMTestValue) {
    this.dKIMTestValue = dKIMTestValue;
    return this;
  }

   /**
   * Get dKIMTestValue
   * @return dKIMTestValue
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getDKIMTestValue() {
    return dKIMTestValue;
  }

  public void setDKIMTestValue(String dKIMTestValue) {
    this.dKIMTestValue = dKIMTestValue;
  }

  public DKIMRotationResponse dKIMPendingHost(String dKIMPendingHost) {
    this.dKIMPendingHost = dKIMPendingHost;
    return this;
  }

   /**
   * Get dKIMPendingHost
   * @return dKIMPendingHost
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getDKIMPendingHost() {
    return dKIMPendingHost;
  }

  public void setDKIMPendingHost(String dKIMPendingHost) {
    this.dKIMPendingHost = dKIMPendingHost;
  }

  public DKIMRotationResponse dKIMPendingTextValue(String dKIMPendingTextValue) {
    this.dKIMPendingTextValue = dKIMPendingTextValue;
    return this;
  }

   /**
   * Get dKIMPendingTextValue
   * @return dKIMPendingTextValue
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getDKIMPendingTextValue() {
    return dKIMPendingTextValue;
  }

  public void setDKIMPendingTextValue(String dKIMPendingTextValue) {
    this.dKIMPendingTextValue = dKIMPendingTextValue;
  }

  public DKIMRotationResponse dKIMRevokedHost(String dKIMRevokedHost) {
    this.dKIMRevokedHost = dKIMRevokedHost;
    return this;
  }

   /**
   * Get dKIMRevokedHost
   * @return dKIMRevokedHost
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getDKIMRevokedHost() {
    return dKIMRevokedHost;
  }

  public void setDKIMRevokedHost(String dKIMRevokedHost) {
    this.dKIMRevokedHost = dKIMRevokedHost;
  }

  public DKIMRotationResponse dKIMRevokedTextValue(String dKIMRevokedTextValue) {
    this.dKIMRevokedTextValue = dKIMRevokedTextValue;
    return this;
  }

   /**
   * Get dKIMRevokedTextValue
   * @return dKIMRevokedTextValue
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getDKIMRevokedTextValue() {
    return dKIMRevokedTextValue;
  }

  public void setDKIMRevokedTextValue(String dKIMRevokedTextValue) {
    this.dKIMRevokedTextValue = dKIMRevokedTextValue;
  }

  public DKIMRotationResponse safeToRemoveRevokedKeyFromDNS(Boolean safeToRemoveRevokedKeyFromDNS) {
    this.safeToRemoveRevokedKeyFromDNS = safeToRemoveRevokedKeyFromDNS;
    return this;
  }

   /**
   * Get safeToRemoveRevokedKeyFromDNS
   * @return safeToRemoveRevokedKeyFromDNS
  **/
  @ApiModelProperty(example = "null", value = "")
  public Boolean getSafeToRemoveRevokedKeyFromDNS() {
    return safeToRemoveRevokedKeyFromDNS;
  }

  public void setSafeToRemoveRevokedKeyFromDNS(Boolean safeToRemoveRevokedKeyFromDNS) {
    this.safeToRemoveRevokedKeyFromDNS = safeToRemoveRevokedKeyFromDNS;
  }

  public DKIMRotationResponse dKIMUpdateStatus(String dKIMUpdateStatus) {
    this.dKIMUpdateStatus = dKIMUpdateStatus;
    return this;
  }

   /**
   * Get dKIMUpdateStatus
   * @return dKIMUpdateStatus
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getDKIMUpdateStatus() {
    return dKIMUpdateStatus;
  }

  public void setDKIMUpdateStatus(String dKIMUpdateStatus) {
    this.dKIMUpdateStatus = dKIMUpdateStatus;
  }

  public DKIMRotationResponse ID(Long ID) {
    this.ID = ID;
    return this;
  }

   /**
   * Get ID
   * @return ID
  **/
  @ApiModelProperty(example = "null", value = "")
  public Long getID() {
    return ID;
  }

  public void setID(Long ID) {
    this.ID = ID;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DKIMRotationResponse dKIMRotationResponse = (DKIMRotationResponse) o;
    return Objects.equals(this.name, dKIMRotationResponse.name) &&
        Objects.equals(this.dKIMVerified, dKIMRotationResponse.dKIMVerified) &&
        Objects.equals(this.weakDKIM, dKIMRotationResponse.weakDKIM) &&
        Objects.equals(this.dKIMHost, dKIMRotationResponse.dKIMHost) &&
        Objects.equals(this.dKIMTestValue, dKIMRotationResponse.dKIMTestValue) &&
        Objects.equals(this.dKIMPendingHost, dKIMRotationResponse.dKIMPendingHost) &&
        Objects.equals(this.dKIMPendingTextValue, dKIMRotationResponse.dKIMPendingTextValue) &&
        Objects.equals(this.dKIMRevokedHost, dKIMRotationResponse.dKIMRevokedHost) &&
        Objects.equals(this.dKIMRevokedTextValue, dKIMRotationResponse.dKIMRevokedTextValue) &&
        Objects.equals(this.safeToRemoveRevokedKeyFromDNS, dKIMRotationResponse.safeToRemoveRevokedKeyFromDNS) &&
        Objects.equals(this.dKIMUpdateStatus, dKIMRotationResponse.dKIMUpdateStatus) &&
        Objects.equals(this.ID, dKIMRotationResponse.ID);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, dKIMVerified, weakDKIM, dKIMHost, dKIMTestValue, dKIMPendingHost, dKIMPendingTextValue, dKIMRevokedHost, dKIMRevokedTextValue, safeToRemoveRevokedKeyFromDNS, dKIMUpdateStatus, ID);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DKIMRotationResponse {\n");
    
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    dKIMVerified: ").append(toIndentedString(dKIMVerified)).append("\n");
    sb.append("    weakDKIM: ").append(toIndentedString(weakDKIM)).append("\n");
    sb.append("    dKIMHost: ").append(toIndentedString(dKIMHost)).append("\n");
    sb.append("    dKIMTestValue: ").append(toIndentedString(dKIMTestValue)).append("\n");
    sb.append("    dKIMPendingHost: ").append(toIndentedString(dKIMPendingHost)).append("\n");
    sb.append("    dKIMPendingTextValue: ").append(toIndentedString(dKIMPendingTextValue)).append("\n");
    sb.append("    dKIMRevokedHost: ").append(toIndentedString(dKIMRevokedHost)).append("\n");
    sb.append("    dKIMRevokedTextValue: ").append(toIndentedString(dKIMRevokedTextValue)).append("\n");
    sb.append("    safeToRemoveRevokedKeyFromDNS: ").append(toIndentedString(safeToRemoveRevokedKeyFromDNS)).append("\n");
    sb.append("    dKIMUpdateStatus: ").append(toIndentedString(dKIMUpdateStatus)).append("\n");
    sb.append("    ID: ").append(toIndentedString(ID)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

