/*
 * Postmark Account-level API
 * Postmark makes sending and receiving email  incredibly easy. The Account-level API allows users to configure all Servers, Domains, and Sender Signatures associated  with an Account. 
 *
 * OpenAPI spec version: 0.9.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package net.nextpulse.postmarkapp.models.account;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * 
 */
@ApiModel(description = "")
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2017-02-24T16:43:30.269+01:00")
public class DomainInformation {
  @JsonProperty("Name")
  private String name = null;

  @JsonProperty("SPFVerified")
  private Boolean sPFVerified = null;

  @JsonProperty("DKIMVerified")
  private Boolean dKIMVerified = null;

  @JsonProperty("WeakDKIM")
  private Boolean weakDKIM = null;

  @JsonProperty("ReturnPathDomainVerified")
  private Boolean returnPathDomainVerified = null;

  @JsonProperty("ID")
  private Long ID = null;

  public DomainInformation name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public DomainInformation sPFVerified(Boolean sPFVerified) {
    this.sPFVerified = sPFVerified;
    return this;
  }

   /**
   * Get sPFVerified
   * @return sPFVerified
  **/
  @ApiModelProperty(example = "null", value = "")
  public Boolean getSPFVerified() {
    return sPFVerified;
  }

  public void setSPFVerified(Boolean sPFVerified) {
    this.sPFVerified = sPFVerified;
  }

  public DomainInformation dKIMVerified(Boolean dKIMVerified) {
    this.dKIMVerified = dKIMVerified;
    return this;
  }

   /**
   * Get dKIMVerified
   * @return dKIMVerified
  **/
  @ApiModelProperty(example = "null", value = "")
  public Boolean getDKIMVerified() {
    return dKIMVerified;
  }

  public void setDKIMVerified(Boolean dKIMVerified) {
    this.dKIMVerified = dKIMVerified;
  }

  public DomainInformation weakDKIM(Boolean weakDKIM) {
    this.weakDKIM = weakDKIM;
    return this;
  }

   /**
   * Get weakDKIM
   * @return weakDKIM
  **/
  @ApiModelProperty(example = "null", value = "")
  public Boolean getWeakDKIM() {
    return weakDKIM;
  }

  public void setWeakDKIM(Boolean weakDKIM) {
    this.weakDKIM = weakDKIM;
  }

  public DomainInformation returnPathDomainVerified(Boolean returnPathDomainVerified) {
    this.returnPathDomainVerified = returnPathDomainVerified;
    return this;
  }

   /**
   * Get returnPathDomainVerified
   * @return returnPathDomainVerified
  **/
  @ApiModelProperty(example = "null", value = "")
  public Boolean getReturnPathDomainVerified() {
    return returnPathDomainVerified;
  }

  public void setReturnPathDomainVerified(Boolean returnPathDomainVerified) {
    this.returnPathDomainVerified = returnPathDomainVerified;
  }

  public DomainInformation ID(Long ID) {
    this.ID = ID;
    return this;
  }

   /**
   * Get ID
   * @return ID
  **/
  @ApiModelProperty(example = "null", value = "")
  public Long getID() {
    return ID;
  }

  public void setID(Long ID) {
    this.ID = ID;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DomainInformation domainInformation = (DomainInformation) o;
    return Objects.equals(this.name, domainInformation.name) &&
        Objects.equals(this.sPFVerified, domainInformation.sPFVerified) &&
        Objects.equals(this.dKIMVerified, domainInformation.dKIMVerified) &&
        Objects.equals(this.weakDKIM, domainInformation.weakDKIM) &&
        Objects.equals(this.returnPathDomainVerified, domainInformation.returnPathDomainVerified) &&
        Objects.equals(this.ID, domainInformation.ID);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, sPFVerified, dKIMVerified, weakDKIM, returnPathDomainVerified, ID);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DomainInformation {\n");
    
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    sPFVerified: ").append(toIndentedString(sPFVerified)).append("\n");
    sb.append("    dKIMVerified: ").append(toIndentedString(dKIMVerified)).append("\n");
    sb.append("    weakDKIM: ").append(toIndentedString(weakDKIM)).append("\n");
    sb.append("    returnPathDomainVerified: ").append(toIndentedString(returnPathDomainVerified)).append("\n");
    sb.append("    ID: ").append(toIndentedString(ID)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

