/*
 * Postmark Account-level API
 * Postmark makes sending and receiving email  incredibly easy. The Account-level API allows users to configure all Servers, Domains, and Sender Signatures associated  with an Account. 
 *
 * OpenAPI spec version: 0.9.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package net.nextpulse.postmarkapp.models.account;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * 
 */
@ApiModel(description = "")
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2017-02-24T16:43:30.269+01:00")
public class DomainSPFResult {
  @JsonProperty("SPFHost")
  private String sPFHost = null;

  @JsonProperty("SPFVerified")
  private Boolean sPFVerified = null;

  @JsonProperty("SPFTextValue")
  private String sPFTextValue = null;

  public DomainSPFResult sPFHost(String sPFHost) {
    this.sPFHost = sPFHost;
    return this;
  }

   /**
   * Get sPFHost
   * @return sPFHost
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getSPFHost() {
    return sPFHost;
  }

  public void setSPFHost(String sPFHost) {
    this.sPFHost = sPFHost;
  }

  public DomainSPFResult sPFVerified(Boolean sPFVerified) {
    this.sPFVerified = sPFVerified;
    return this;
  }

   /**
   * Get sPFVerified
   * @return sPFVerified
  **/
  @ApiModelProperty(example = "null", value = "")
  public Boolean getSPFVerified() {
    return sPFVerified;
  }

  public void setSPFVerified(Boolean sPFVerified) {
    this.sPFVerified = sPFVerified;
  }

  public DomainSPFResult sPFTextValue(String sPFTextValue) {
    this.sPFTextValue = sPFTextValue;
    return this;
  }

   /**
   * Get sPFTextValue
   * @return sPFTextValue
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getSPFTextValue() {
    return sPFTextValue;
  }

  public void setSPFTextValue(String sPFTextValue) {
    this.sPFTextValue = sPFTextValue;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DomainSPFResult domainSPFResult = (DomainSPFResult) o;
    return Objects.equals(this.sPFHost, domainSPFResult.sPFHost) &&
        Objects.equals(this.sPFVerified, domainSPFResult.sPFVerified) &&
        Objects.equals(this.sPFTextValue, domainSPFResult.sPFTextValue);
  }

  @Override
  public int hashCode() {
    return Objects.hash(sPFHost, sPFVerified, sPFTextValue);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DomainSPFResult {\n");
    
    sb.append("    sPFHost: ").append(toIndentedString(sPFHost)).append("\n");
    sb.append("    sPFVerified: ").append(toIndentedString(sPFVerified)).append("\n");
    sb.append("    sPFTextValue: ").append(toIndentedString(sPFTextValue)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

