/*
 * Postmark Account-level API
 * Postmark makes sending and receiving email  incredibly easy. The Account-level API allows users to configure all Servers, Domains, and Sender Signatures associated  with an Account. 
 *
 * OpenAPI spec version: 0.9.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package net.nextpulse.postmarkapp.models.account;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import net.nextpulse.postmarkapp.models.account.SenderSignatureInformation;

/**
 * 
 */
@ApiModel(description = "")
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2017-02-24T16:43:30.269+01:00")
public class SenderListingResults {
  @JsonProperty("TotalCount")
  private Integer totalCount = null;

  @JsonProperty("SenderSignatures")
  private List<SenderSignatureInformation> senderSignatures = new ArrayList<SenderSignatureInformation>();

  public SenderListingResults totalCount(Integer totalCount) {
    this.totalCount = totalCount;
    return this;
  }

   /**
   * Get totalCount
   * @return totalCount
  **/
  @ApiModelProperty(example = "null", value = "")
  public Integer getTotalCount() {
    return totalCount;
  }

  public void setTotalCount(Integer totalCount) {
    this.totalCount = totalCount;
  }

  public SenderListingResults senderSignatures(List<SenderSignatureInformation> senderSignatures) {
    this.senderSignatures = senderSignatures;
    return this;
  }

  public SenderListingResults addSenderSignaturesItem(SenderSignatureInformation senderSignaturesItem) {
    this.senderSignatures.add(senderSignaturesItem);
    return this;
  }

   /**
   * Get senderSignatures
   * @return senderSignatures
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<SenderSignatureInformation> getSenderSignatures() {
    return senderSignatures;
  }

  public void setSenderSignatures(List<SenderSignatureInformation> senderSignatures) {
    this.senderSignatures = senderSignatures;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SenderListingResults senderListingResults = (SenderListingResults) o;
    return Objects.equals(this.totalCount, senderListingResults.totalCount) &&
        Objects.equals(this.senderSignatures, senderListingResults.senderSignatures);
  }

  @Override
  public int hashCode() {
    return Objects.hash(totalCount, senderSignatures);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SenderListingResults {\n");
    
    sb.append("    totalCount: ").append(toIndentedString(totalCount)).append("\n");
    sb.append("    senderSignatures: ").append(toIndentedString(senderSignatures)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

