/*
 * Postmark API
 * Postmark makes sending and receiving email incredibly easy. 
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package net.nextpulse.postmarkapp.models.server;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import net.nextpulse.postmarkapp.models.server.BounceInfoResponse;

/**
 * 
 */
@ApiModel(description = "")
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2017-02-24T16:43:29.220+01:00")
public class BounceSearchResponse {
  @JsonProperty("TotalCount")
  private Integer totalCount = null;

  @JsonProperty("Bounces")
  private List<BounceInfoResponse> bounces = new ArrayList<BounceInfoResponse>();

  public BounceSearchResponse totalCount(Integer totalCount) {
    this.totalCount = totalCount;
    return this;
  }

   /**
   * Get totalCount
   * @return totalCount
  **/
  @ApiModelProperty(example = "null", value = "")
  public Integer getTotalCount() {
    return totalCount;
  }

  public void setTotalCount(Integer totalCount) {
    this.totalCount = totalCount;
  }

  public BounceSearchResponse bounces(List<BounceInfoResponse> bounces) {
    this.bounces = bounces;
    return this;
  }

  public BounceSearchResponse addBouncesItem(BounceInfoResponse bouncesItem) {
    this.bounces.add(bouncesItem);
    return this;
  }

   /**
   * Get bounces
   * @return bounces
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<BounceInfoResponse> getBounces() {
    return bounces;
  }

  public void setBounces(List<BounceInfoResponse> bounces) {
    this.bounces = bounces;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BounceSearchResponse bounceSearchResponse = (BounceSearchResponse) o;
    return Objects.equals(this.totalCount, bounceSearchResponse.totalCount) &&
        Objects.equals(this.bounces, bounceSearchResponse.bounces);
  }

  @Override
  public int hashCode() {
    return Objects.hash(totalCount, bounces);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BounceSearchResponse {\n");
    
    sb.append("    totalCount: ").append(toIndentedString(totalCount)).append("\n");
    sb.append("    bounces: ").append(toIndentedString(bounces)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

