/*
 * Postmark API
 * Postmark makes sending and receiving email incredibly easy. 
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package net.nextpulse.postmarkapp.models.server;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.Date;
import net.nextpulse.postmarkapp.models.server.ExtendedMessageOpenEventInformationClient;
import net.nextpulse.postmarkapp.models.server.ExtendedMessageOpenEventInformationGeo;
import net.nextpulse.postmarkapp.models.server.ExtendedMessageOpenEventInformationOS;

/**
 * 
 */
@ApiModel(description = "")
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2017-02-24T16:43:29.220+01:00")
public class ExtendedMessageOpenEventInformation {
  @JsonProperty("FirstOpen")
  private Boolean firstOpen = null;

  @JsonProperty("Client")
  private ExtendedMessageOpenEventInformationClient client = null;

  @JsonProperty("OS")
  private ExtendedMessageOpenEventInformationOS OS = null;

  @JsonProperty("Platform")
  private String platform = null;

  @JsonProperty("UserAgent")
  private String userAgent = null;

  @JsonProperty("ReadSeconds")
  private String readSeconds = null;

  @JsonProperty("Geo")
  private ExtendedMessageOpenEventInformationGeo geo = null;

  @JsonProperty("MessageID")
  private String messageID = null;

  @JsonProperty("ReceivedAt")
  private Date receivedAt = null;

  @JsonProperty("Tag")
  private String tag = null;

  @JsonProperty("Recipient")
  private String recipient = null;

  public ExtendedMessageOpenEventInformation firstOpen(Boolean firstOpen) {
    this.firstOpen = firstOpen;
    return this;
  }

   /**
   * Get firstOpen
   * @return firstOpen
  **/
  @ApiModelProperty(example = "null", value = "")
  public Boolean getFirstOpen() {
    return firstOpen;
  }

  public void setFirstOpen(Boolean firstOpen) {
    this.firstOpen = firstOpen;
  }

  public ExtendedMessageOpenEventInformation client(ExtendedMessageOpenEventInformationClient client) {
    this.client = client;
    return this;
  }

   /**
   * Get client
   * @return client
  **/
  @ApiModelProperty(example = "null", value = "")
  public ExtendedMessageOpenEventInformationClient getClient() {
    return client;
  }

  public void setClient(ExtendedMessageOpenEventInformationClient client) {
    this.client = client;
  }

  public ExtendedMessageOpenEventInformation OS(ExtendedMessageOpenEventInformationOS OS) {
    this.OS = OS;
    return this;
  }

   /**
   * Get OS
   * @return OS
  **/
  @ApiModelProperty(example = "null", value = "")
  public ExtendedMessageOpenEventInformationOS getOS() {
    return OS;
  }

  public void setOS(ExtendedMessageOpenEventInformationOS OS) {
    this.OS = OS;
  }

  public ExtendedMessageOpenEventInformation platform(String platform) {
    this.platform = platform;
    return this;
  }

   /**
   * Get platform
   * @return platform
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getPlatform() {
    return platform;
  }

  public void setPlatform(String platform) {
    this.platform = platform;
  }

  public ExtendedMessageOpenEventInformation userAgent(String userAgent) {
    this.userAgent = userAgent;
    return this;
  }

   /**
   * Get userAgent
   * @return userAgent
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getUserAgent() {
    return userAgent;
  }

  public void setUserAgent(String userAgent) {
    this.userAgent = userAgent;
  }

  public ExtendedMessageOpenEventInformation readSeconds(String readSeconds) {
    this.readSeconds = readSeconds;
    return this;
  }

   /**
   * Get readSeconds
   * @return readSeconds
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getReadSeconds() {
    return readSeconds;
  }

  public void setReadSeconds(String readSeconds) {
    this.readSeconds = readSeconds;
  }

  public ExtendedMessageOpenEventInformation geo(ExtendedMessageOpenEventInformationGeo geo) {
    this.geo = geo;
    return this;
  }

   /**
   * Get geo
   * @return geo
  **/
  @ApiModelProperty(example = "null", value = "")
  public ExtendedMessageOpenEventInformationGeo getGeo() {
    return geo;
  }

  public void setGeo(ExtendedMessageOpenEventInformationGeo geo) {
    this.geo = geo;
  }

  public ExtendedMessageOpenEventInformation messageID(String messageID) {
    this.messageID = messageID;
    return this;
  }

   /**
   * Get messageID
   * @return messageID
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getMessageID() {
    return messageID;
  }

  public void setMessageID(String messageID) {
    this.messageID = messageID;
  }

  public ExtendedMessageOpenEventInformation receivedAt(Date receivedAt) {
    this.receivedAt = receivedAt;
    return this;
  }

   /**
   * Get receivedAt
   * @return receivedAt
  **/
  @ApiModelProperty(example = "null", value = "")
  public Date getReceivedAt() {
    return receivedAt;
  }

  public void setReceivedAt(Date receivedAt) {
    this.receivedAt = receivedAt;
  }

  public ExtendedMessageOpenEventInformation tag(String tag) {
    this.tag = tag;
    return this;
  }

   /**
   * Get tag
   * @return tag
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getTag() {
    return tag;
  }

  public void setTag(String tag) {
    this.tag = tag;
  }

  public ExtendedMessageOpenEventInformation recipient(String recipient) {
    this.recipient = recipient;
    return this;
  }

   /**
   * Get recipient
   * @return recipient
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getRecipient() {
    return recipient;
  }

  public void setRecipient(String recipient) {
    this.recipient = recipient;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ExtendedMessageOpenEventInformation extendedMessageOpenEventInformation = (ExtendedMessageOpenEventInformation) o;
    return Objects.equals(this.firstOpen, extendedMessageOpenEventInformation.firstOpen) &&
        Objects.equals(this.client, extendedMessageOpenEventInformation.client) &&
        Objects.equals(this.OS, extendedMessageOpenEventInformation.OS) &&
        Objects.equals(this.platform, extendedMessageOpenEventInformation.platform) &&
        Objects.equals(this.userAgent, extendedMessageOpenEventInformation.userAgent) &&
        Objects.equals(this.readSeconds, extendedMessageOpenEventInformation.readSeconds) &&
        Objects.equals(this.geo, extendedMessageOpenEventInformation.geo) &&
        Objects.equals(this.messageID, extendedMessageOpenEventInformation.messageID) &&
        Objects.equals(this.receivedAt, extendedMessageOpenEventInformation.receivedAt) &&
        Objects.equals(this.tag, extendedMessageOpenEventInformation.tag) &&
        Objects.equals(this.recipient, extendedMessageOpenEventInformation.recipient);
  }

  @Override
  public int hashCode() {
    return Objects.hash(firstOpen, client, OS, platform, userAgent, readSeconds, geo, messageID, receivedAt, tag, recipient);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ExtendedMessageOpenEventInformation {\n");
    
    sb.append("    firstOpen: ").append(toIndentedString(firstOpen)).append("\n");
    sb.append("    client: ").append(toIndentedString(client)).append("\n");
    sb.append("    OS: ").append(toIndentedString(OS)).append("\n");
    sb.append("    platform: ").append(toIndentedString(platform)).append("\n");
    sb.append("    userAgent: ").append(toIndentedString(userAgent)).append("\n");
    sb.append("    readSeconds: ").append(toIndentedString(readSeconds)).append("\n");
    sb.append("    geo: ").append(toIndentedString(geo)).append("\n");
    sb.append("    messageID: ").append(toIndentedString(messageID)).append("\n");
    sb.append("    receivedAt: ").append(toIndentedString(receivedAt)).append("\n");
    sb.append("    tag: ").append(toIndentedString(tag)).append("\n");
    sb.append("    recipient: ").append(toIndentedString(recipient)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

