/*
 * Postmark API
 * Postmark makes sending and receiving email incredibly easy. 
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package net.nextpulse.postmarkapp.models.server;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * ExtendedMessageOpenEventInformationGeo
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2017-02-24T16:43:29.220+01:00")
public class ExtendedMessageOpenEventInformationGeo {
  @JsonProperty("CountryISOCode")
  private String countryISOCode = null;

  @JsonProperty("Country")
  private String country = null;

  @JsonProperty("RegionISOCode")
  private String regionISOCode = null;

  @JsonProperty("Region")
  private String region = null;

  @JsonProperty("City")
  private String city = null;

  @JsonProperty("Zip")
  private String zip = null;

  @JsonProperty("Coords")
  private String coords = null;

  @JsonProperty("IP")
  private String IP = null;

  public ExtendedMessageOpenEventInformationGeo countryISOCode(String countryISOCode) {
    this.countryISOCode = countryISOCode;
    return this;
  }

   /**
   * Get countryISOCode
   * @return countryISOCode
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getCountryISOCode() {
    return countryISOCode;
  }

  public void setCountryISOCode(String countryISOCode) {
    this.countryISOCode = countryISOCode;
  }

  public ExtendedMessageOpenEventInformationGeo country(String country) {
    this.country = country;
    return this;
  }

   /**
   * Get country
   * @return country
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getCountry() {
    return country;
  }

  public void setCountry(String country) {
    this.country = country;
  }

  public ExtendedMessageOpenEventInformationGeo regionISOCode(String regionISOCode) {
    this.regionISOCode = regionISOCode;
    return this;
  }

   /**
   * Get regionISOCode
   * @return regionISOCode
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getRegionISOCode() {
    return regionISOCode;
  }

  public void setRegionISOCode(String regionISOCode) {
    this.regionISOCode = regionISOCode;
  }

  public ExtendedMessageOpenEventInformationGeo region(String region) {
    this.region = region;
    return this;
  }

   /**
   * Get region
   * @return region
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getRegion() {
    return region;
  }

  public void setRegion(String region) {
    this.region = region;
  }

  public ExtendedMessageOpenEventInformationGeo city(String city) {
    this.city = city;
    return this;
  }

   /**
   * Get city
   * @return city
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getCity() {
    return city;
  }

  public void setCity(String city) {
    this.city = city;
  }

  public ExtendedMessageOpenEventInformationGeo zip(String zip) {
    this.zip = zip;
    return this;
  }

   /**
   * Get zip
   * @return zip
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getZip() {
    return zip;
  }

  public void setZip(String zip) {
    this.zip = zip;
  }

  public ExtendedMessageOpenEventInformationGeo coords(String coords) {
    this.coords = coords;
    return this;
  }

   /**
   * Get coords
   * @return coords
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getCoords() {
    return coords;
  }

  public void setCoords(String coords) {
    this.coords = coords;
  }

  public ExtendedMessageOpenEventInformationGeo IP(String IP) {
    this.IP = IP;
    return this;
  }

   /**
   * Get IP
   * @return IP
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getIP() {
    return IP;
  }

  public void setIP(String IP) {
    this.IP = IP;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ExtendedMessageOpenEventInformationGeo extendedMessageOpenEventInformationGeo = (ExtendedMessageOpenEventInformationGeo) o;
    return Objects.equals(this.countryISOCode, extendedMessageOpenEventInformationGeo.countryISOCode) &&
        Objects.equals(this.country, extendedMessageOpenEventInformationGeo.country) &&
        Objects.equals(this.regionISOCode, extendedMessageOpenEventInformationGeo.regionISOCode) &&
        Objects.equals(this.region, extendedMessageOpenEventInformationGeo.region) &&
        Objects.equals(this.city, extendedMessageOpenEventInformationGeo.city) &&
        Objects.equals(this.zip, extendedMessageOpenEventInformationGeo.zip) &&
        Objects.equals(this.coords, extendedMessageOpenEventInformationGeo.coords) &&
        Objects.equals(this.IP, extendedMessageOpenEventInformationGeo.IP);
  }

  @Override
  public int hashCode() {
    return Objects.hash(countryISOCode, country, regionISOCode, region, city, zip, coords, IP);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ExtendedMessageOpenEventInformationGeo {\n");
    
    sb.append("    countryISOCode: ").append(toIndentedString(countryISOCode)).append("\n");
    sb.append("    country: ").append(toIndentedString(country)).append("\n");
    sb.append("    regionISOCode: ").append(toIndentedString(regionISOCode)).append("\n");
    sb.append("    region: ").append(toIndentedString(region)).append("\n");
    sb.append("    city: ").append(toIndentedString(city)).append("\n");
    sb.append("    zip: ").append(toIndentedString(zip)).append("\n");
    sb.append("    coords: ").append(toIndentedString(coords)).append("\n");
    sb.append("    IP: ").append(toIndentedString(IP)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

