/*
 * Postmark API
 * Postmark makes sending and receiving email incredibly easy. 
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package net.nextpulse.postmarkapp.models.server;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import net.nextpulse.postmarkapp.models.server.InboundMessageDetail;

/**
 * 
 */
@ApiModel(description = "")
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2017-02-24T16:43:29.220+01:00")
public class InboundSearchResponse {
  @JsonProperty("TotalCount")
  private Integer totalCount = null;

  @JsonProperty("InboundMessages")
  private List<InboundMessageDetail> inboundMessages = new ArrayList<InboundMessageDetail>();

  public InboundSearchResponse totalCount(Integer totalCount) {
    this.totalCount = totalCount;
    return this;
  }

   /**
   * Get totalCount
   * @return totalCount
  **/
  @ApiModelProperty(example = "null", value = "")
  public Integer getTotalCount() {
    return totalCount;
  }

  public void setTotalCount(Integer totalCount) {
    this.totalCount = totalCount;
  }

  public InboundSearchResponse inboundMessages(List<InboundMessageDetail> inboundMessages) {
    this.inboundMessages = inboundMessages;
    return this;
  }

  public InboundSearchResponse addInboundMessagesItem(InboundMessageDetail inboundMessagesItem) {
    this.inboundMessages.add(inboundMessagesItem);
    return this;
  }

   /**
   * Get inboundMessages
   * @return inboundMessages
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<InboundMessageDetail> getInboundMessages() {
    return inboundMessages;
  }

  public void setInboundMessages(List<InboundMessageDetail> inboundMessages) {
    this.inboundMessages = inboundMessages;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InboundSearchResponse inboundSearchResponse = (InboundSearchResponse) o;
    return Objects.equals(this.totalCount, inboundSearchResponse.totalCount) &&
        Objects.equals(this.inboundMessages, inboundSearchResponse.inboundMessages);
  }

  @Override
  public int hashCode() {
    return Objects.hash(totalCount, inboundMessages);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InboundSearchResponse {\n");
    
    sb.append("    totalCount: ").append(toIndentedString(totalCount)).append("\n");
    sb.append("    inboundMessages: ").append(toIndentedString(inboundMessages)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

