/*
 * Postmark API
 * Postmark makes sending and receiving email incredibly easy. 
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package net.nextpulse.postmarkapp.models.server;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * InlineResponse2005Days
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2017-02-24T16:43:29.220+01:00")
public class InlineResponse2005Days {
  @JsonProperty("Date")
  private String date = null;

  @JsonProperty("Tracked")
  private Integer tracked = null;

  public InlineResponse2005Days date(String date) {
    this.date = date;
    return this;
  }

   /**
   * Get date
   * @return date
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getDate() {
    return date;
  }

  public void setDate(String date) {
    this.date = date;
  }

  public InlineResponse2005Days tracked(Integer tracked) {
    this.tracked = tracked;
    return this;
  }

   /**
   * Get tracked
   * @return tracked
  **/
  @ApiModelProperty(example = "null", value = "")
  public Integer getTracked() {
    return tracked;
  }

  public void setTracked(Integer tracked) {
    this.tracked = tracked;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InlineResponse2005Days inlineResponse2005Days = (InlineResponse2005Days) o;
    return Objects.equals(this.date, inlineResponse2005Days.date) &&
        Objects.equals(this.tracked, inlineResponse2005Days.tracked);
  }

  @Override
  public int hashCode() {
    return Objects.hash(date, tracked);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InlineResponse2005Days {\n");
    
    sb.append("    date: ").append(toIndentedString(date)).append("\n");
    sb.append("    tracked: ").append(toIndentedString(tracked)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

