/*
 * Postmark API
 * Postmark makes sending and receiving email incredibly easy. 
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package net.nextpulse.postmarkapp.models.server;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import net.nextpulse.postmarkapp.models.server.DynamicResponse;

/**
 * InlineResponse2002
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2017-02-24T16:43:29.220+01:00")
public class InlineResponse2002 {
  @JsonProperty("Desktop")
  private Integer desktop = null;

  @JsonProperty("WebMail")
  private Integer webMail = null;

  @JsonProperty("Mobile")
  private Integer mobile = null;

  @JsonProperty("Unknown")
  private Integer unknown = null;

  @JsonProperty("Days")
  private List<DynamicResponse> days = new ArrayList<DynamicResponse>();

  public InlineResponse2002 desktop(Integer desktop) {
    this.desktop = desktop;
    return this;
  }

   /**
   * Get desktop
   * @return desktop
  **/
  @ApiModelProperty(example = "null", value = "")
  public Integer getDesktop() {
    return desktop;
  }

  public void setDesktop(Integer desktop) {
    this.desktop = desktop;
  }

  public InlineResponse2002 webMail(Integer webMail) {
    this.webMail = webMail;
    return this;
  }

   /**
   * Get webMail
   * @return webMail
  **/
  @ApiModelProperty(example = "null", value = "")
  public Integer getWebMail() {
    return webMail;
  }

  public void setWebMail(Integer webMail) {
    this.webMail = webMail;
  }

  public InlineResponse2002 mobile(Integer mobile) {
    this.mobile = mobile;
    return this;
  }

   /**
   * Get mobile
   * @return mobile
  **/
  @ApiModelProperty(example = "null", value = "")
  public Integer getMobile() {
    return mobile;
  }

  public void setMobile(Integer mobile) {
    this.mobile = mobile;
  }

  public InlineResponse2002 unknown(Integer unknown) {
    this.unknown = unknown;
    return this;
  }

   /**
   * Get unknown
   * @return unknown
  **/
  @ApiModelProperty(example = "null", value = "")
  public Integer getUnknown() {
    return unknown;
  }

  public void setUnknown(Integer unknown) {
    this.unknown = unknown;
  }

  public InlineResponse2002 days(List<DynamicResponse> days) {
    this.days = days;
    return this;
  }

  public InlineResponse2002 addDaysItem(DynamicResponse daysItem) {
    this.days.add(daysItem);
    return this;
  }

   /**
   * Get days
   * @return days
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<DynamicResponse> getDays() {
    return days;
  }

  public void setDays(List<DynamicResponse> days) {
    this.days = days;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InlineResponse2002 inlineResponse2002 = (InlineResponse2002) o;
    return Objects.equals(this.desktop, inlineResponse2002.desktop) &&
        Objects.equals(this.webMail, inlineResponse2002.webMail) &&
        Objects.equals(this.mobile, inlineResponse2002.mobile) &&
        Objects.equals(this.unknown, inlineResponse2002.unknown) &&
        Objects.equals(this.days, inlineResponse2002.days);
  }

  @Override
  public int hashCode() {
    return Objects.hash(desktop, webMail, mobile, unknown, days);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InlineResponse2002 {\n");
    
    sb.append("    desktop: ").append(toIndentedString(desktop)).append("\n");
    sb.append("    webMail: ").append(toIndentedString(webMail)).append("\n");
    sb.append("    mobile: ").append(toIndentedString(mobile)).append("\n");
    sb.append("    unknown: ").append(toIndentedString(unknown)).append("\n");
    sb.append("    days: ").append(toIndentedString(days)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

