/*
 * Postmark API
 * Postmark makes sending and receiving email incredibly easy. 
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package net.nextpulse.postmarkapp.models.server;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * InlineResponse200Days
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2017-02-24T16:43:29.220+01:00")
public class InlineResponse200Days {
  @JsonProperty("Date")
  private String date = null;

  @JsonProperty("HardBounce")
  private Integer hardBounce = null;

  @JsonProperty("SoftBounce")
  private Integer softBounce = null;

  @JsonProperty("SMTPApiError")
  private Integer sMTPApiError = null;

  @JsonProperty("Transient")
  private Integer _transient = null;

  public InlineResponse200Days date(String date) {
    this.date = date;
    return this;
  }

   /**
   * Get date
   * @return date
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getDate() {
    return date;
  }

  public void setDate(String date) {
    this.date = date;
  }

  public InlineResponse200Days hardBounce(Integer hardBounce) {
    this.hardBounce = hardBounce;
    return this;
  }

   /**
   * Get hardBounce
   * @return hardBounce
  **/
  @ApiModelProperty(example = "null", value = "")
  public Integer getHardBounce() {
    return hardBounce;
  }

  public void setHardBounce(Integer hardBounce) {
    this.hardBounce = hardBounce;
  }

  public InlineResponse200Days softBounce(Integer softBounce) {
    this.softBounce = softBounce;
    return this;
  }

   /**
   * Get softBounce
   * @return softBounce
  **/
  @ApiModelProperty(example = "null", value = "")
  public Integer getSoftBounce() {
    return softBounce;
  }

  public void setSoftBounce(Integer softBounce) {
    this.softBounce = softBounce;
  }

  public InlineResponse200Days sMTPApiError(Integer sMTPApiError) {
    this.sMTPApiError = sMTPApiError;
    return this;
  }

   /**
   * Get sMTPApiError
   * @return sMTPApiError
  **/
  @ApiModelProperty(example = "null", value = "")
  public Integer getSMTPApiError() {
    return sMTPApiError;
  }

  public void setSMTPApiError(Integer sMTPApiError) {
    this.sMTPApiError = sMTPApiError;
  }

  public InlineResponse200Days _transient(Integer _transient) {
    this._transient = _transient;
    return this;
  }

   /**
   * Get _transient
   * @return _transient
  **/
  @ApiModelProperty(example = "null", value = "")
  public Integer getTransient() {
    return _transient;
  }

  public void setTransient(Integer _transient) {
    this._transient = _transient;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InlineResponse200Days inlineResponse200Days = (InlineResponse200Days) o;
    return Objects.equals(this.date, inlineResponse200Days.date) &&
        Objects.equals(this.hardBounce, inlineResponse200Days.hardBounce) &&
        Objects.equals(this.softBounce, inlineResponse200Days.softBounce) &&
        Objects.equals(this.sMTPApiError, inlineResponse200Days.sMTPApiError) &&
        Objects.equals(this._transient, inlineResponse200Days._transient);
  }

  @Override
  public int hashCode() {
    return Objects.hash(date, hardBounce, softBounce, sMTPApiError, _transient);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InlineResponse200Days {\n");
    
    sb.append("    date: ").append(toIndentedString(date)).append("\n");
    sb.append("    hardBounce: ").append(toIndentedString(hardBounce)).append("\n");
    sb.append("    softBounce: ").append(toIndentedString(softBounce)).append("\n");
    sb.append("    sMTPApiError: ").append(toIndentedString(sMTPApiError)).append("\n");
    sb.append("    _transient: ").append(toIndentedString(_transient)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

