/*
 * Postmark API
 * Postmark makes sending and receiving email incredibly easy. 
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package net.nextpulse.postmarkapp.models.server;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import net.nextpulse.postmarkapp.models.server.ExtendedMessageOpenEventInformation;

/**
 * MessageOpenSearchResponse
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2017-02-24T16:43:29.220+01:00")
public class MessageOpenSearchResponse {
  @JsonProperty("TotalCount")
  private Integer totalCount = null;

  @JsonProperty("Opens")
  private List<ExtendedMessageOpenEventInformation> opens = new ArrayList<ExtendedMessageOpenEventInformation>();

  public MessageOpenSearchResponse totalCount(Integer totalCount) {
    this.totalCount = totalCount;
    return this;
  }

   /**
   * Get totalCount
   * @return totalCount
  **/
  @ApiModelProperty(example = "null", value = "")
  public Integer getTotalCount() {
    return totalCount;
  }

  public void setTotalCount(Integer totalCount) {
    this.totalCount = totalCount;
  }

  public MessageOpenSearchResponse opens(List<ExtendedMessageOpenEventInformation> opens) {
    this.opens = opens;
    return this;
  }

  public MessageOpenSearchResponse addOpensItem(ExtendedMessageOpenEventInformation opensItem) {
    this.opens.add(opensItem);
    return this;
  }

   /**
   * Get opens
   * @return opens
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<ExtendedMessageOpenEventInformation> getOpens() {
    return opens;
  }

  public void setOpens(List<ExtendedMessageOpenEventInformation> opens) {
    this.opens = opens;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MessageOpenSearchResponse messageOpenSearchResponse = (MessageOpenSearchResponse) o;
    return Objects.equals(this.totalCount, messageOpenSearchResponse.totalCount) &&
        Objects.equals(this.opens, messageOpenSearchResponse.opens);
  }

  @Override
  public int hashCode() {
    return Objects.hash(totalCount, opens);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MessageOpenSearchResponse {\n");
    
    sb.append("    totalCount: ").append(toIndentedString(totalCount)).append("\n");
    sb.append("    opens: ").append(toIndentedString(opens)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

