/*
 * Postmark API
 * Postmark makes sending and receiving email incredibly easy. 
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package net.nextpulse.postmarkapp.models.server;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import net.nextpulse.postmarkapp.models.server.SentCountsResponseDays;

/**
 * The result of a get sent counts operation.
 */
@ApiModel(description = "The result of a get sent counts operation.")
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2017-02-24T16:43:29.220+01:00")
public class SentCountsResponse {
  @JsonProperty("Sent")
  private Integer sent = null;

  @JsonProperty("Days")
  private List<SentCountsResponseDays> days = new ArrayList<SentCountsResponseDays>();

  public SentCountsResponse sent(Integer sent) {
    this.sent = sent;
    return this;
  }

   /**
   * Get sent
   * @return sent
  **/
  @ApiModelProperty(example = "null", value = "")
  public Integer getSent() {
    return sent;
  }

  public void setSent(Integer sent) {
    this.sent = sent;
  }

  public SentCountsResponse days(List<SentCountsResponseDays> days) {
    this.days = days;
    return this;
  }

  public SentCountsResponse addDaysItem(SentCountsResponseDays daysItem) {
    this.days.add(daysItem);
    return this;
  }

   /**
   * Get days
   * @return days
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<SentCountsResponseDays> getDays() {
    return days;
  }

  public void setDays(List<SentCountsResponseDays> days) {
    this.days = days;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SentCountsResponse sentCountsResponse = (SentCountsResponse) o;
    return Objects.equals(this.sent, sentCountsResponse.sent) &&
        Objects.equals(this.days, sentCountsResponse.days);
  }

  @Override
  public int hashCode() {
    return Objects.hash(sent, days);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SentCountsResponse {\n");
    
    sb.append("    sent: ").append(toIndentedString(sent)).append("\n");
    sb.append("    days: ").append(toIndentedString(days)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

