/*
 * Postmark API
 * Postmark makes sending and receiving email incredibly easy. 
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package net.nextpulse.postmarkapp.models.server;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import net.nextpulse.postmarkapp.models.server.TemplateValidationResult;

/**
 * TemplateValidationResponse
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2017-02-24T16:43:29.220+01:00")
public class TemplateValidationResponse {
  @JsonProperty("AllContentIsValid")
  private Boolean allContentIsValid = null;

  @JsonProperty("TextBody")
  private TemplateValidationResult textBody = null;

  @JsonProperty("HtmlBody")
  private TemplateValidationResult htmlBody = null;

  @JsonProperty("Subject")
  private TemplateValidationResult subject = null;

  @JsonProperty("SuggestedTemplateModel")
  private Object suggestedTemplateModel = null;

  public TemplateValidationResponse allContentIsValid(Boolean allContentIsValid) {
    this.allContentIsValid = allContentIsValid;
    return this;
  }

   /**
   * Get allContentIsValid
   * @return allContentIsValid
  **/
  @ApiModelProperty(example = "null", value = "")
  public Boolean getAllContentIsValid() {
    return allContentIsValid;
  }

  public void setAllContentIsValid(Boolean allContentIsValid) {
    this.allContentIsValid = allContentIsValid;
  }

  public TemplateValidationResponse textBody(TemplateValidationResult textBody) {
    this.textBody = textBody;
    return this;
  }

   /**
   * Get textBody
   * @return textBody
  **/
  @ApiModelProperty(example = "null", value = "")
  public TemplateValidationResult getTextBody() {
    return textBody;
  }

  public void setTextBody(TemplateValidationResult textBody) {
    this.textBody = textBody;
  }

  public TemplateValidationResponse htmlBody(TemplateValidationResult htmlBody) {
    this.htmlBody = htmlBody;
    return this;
  }

   /**
   * Get htmlBody
   * @return htmlBody
  **/
  @ApiModelProperty(example = "null", value = "")
  public TemplateValidationResult getHtmlBody() {
    return htmlBody;
  }

  public void setHtmlBody(TemplateValidationResult htmlBody) {
    this.htmlBody = htmlBody;
  }

  public TemplateValidationResponse subject(TemplateValidationResult subject) {
    this.subject = subject;
    return this;
  }

   /**
   * Get subject
   * @return subject
  **/
  @ApiModelProperty(example = "null", value = "")
  public TemplateValidationResult getSubject() {
    return subject;
  }

  public void setSubject(TemplateValidationResult subject) {
    this.subject = subject;
  }

  public TemplateValidationResponse suggestedTemplateModel(Object suggestedTemplateModel) {
    this.suggestedTemplateModel = suggestedTemplateModel;
    return this;
  }

   /**
   * Get suggestedTemplateModel
   * @return suggestedTemplateModel
  **/
  @ApiModelProperty(example = "null", value = "")
  public Object getSuggestedTemplateModel() {
    return suggestedTemplateModel;
  }

  public void setSuggestedTemplateModel(Object suggestedTemplateModel) {
    this.suggestedTemplateModel = suggestedTemplateModel;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TemplateValidationResponse templateValidationResponse = (TemplateValidationResponse) o;
    return Objects.equals(this.allContentIsValid, templateValidationResponse.allContentIsValid) &&
        Objects.equals(this.textBody, templateValidationResponse.textBody) &&
        Objects.equals(this.htmlBody, templateValidationResponse.htmlBody) &&
        Objects.equals(this.subject, templateValidationResponse.subject) &&
        Objects.equals(this.suggestedTemplateModel, templateValidationResponse.suggestedTemplateModel);
  }

  @Override
  public int hashCode() {
    return Objects.hash(allContentIsValid, textBody, htmlBody, subject, suggestedTemplateModel);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TemplateValidationResponse {\n");
    
    sb.append("    allContentIsValid: ").append(toIndentedString(allContentIsValid)).append("\n");
    sb.append("    textBody: ").append(toIndentedString(textBody)).append("\n");
    sb.append("    htmlBody: ").append(toIndentedString(htmlBody)).append("\n");
    sb.append("    subject: ").append(toIndentedString(subject)).append("\n");
    sb.append("    suggestedTemplateModel: ").append(toIndentedString(suggestedTemplateModel)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

