/*
 * Postmark API
 * Postmark makes sending and receiving email incredibly easy. 
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package net.nextpulse.postmarkapp.models.server;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * TemplateValidationError
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2017-02-24T16:43:29.220+01:00")
public class TemplateValidationError {
  @JsonProperty("Message")
  private String message = null;

  @JsonProperty("Line")
  private Integer line = null;

  @JsonProperty("CharacterPosition")
  private Integer characterPosition = null;

  public TemplateValidationError message(String message) {
    this.message = message;
    return this;
  }

   /**
   * Get message
   * @return message
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getMessage() {
    return message;
  }

  public void setMessage(String message) {
    this.message = message;
  }

  public TemplateValidationError line(Integer line) {
    this.line = line;
    return this;
  }

   /**
   * Get line
   * @return line
  **/
  @ApiModelProperty(example = "null", value = "")
  public Integer getLine() {
    return line;
  }

  public void setLine(Integer line) {
    this.line = line;
  }

  public TemplateValidationError characterPosition(Integer characterPosition) {
    this.characterPosition = characterPosition;
    return this;
  }

   /**
   * Get characterPosition
   * @return characterPosition
  **/
  @ApiModelProperty(example = "null", value = "")
  public Integer getCharacterPosition() {
    return characterPosition;
  }

  public void setCharacterPosition(Integer characterPosition) {
    this.characterPosition = characterPosition;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TemplateValidationError templateValidationError = (TemplateValidationError) o;
    return Objects.equals(this.message, templateValidationError.message) &&
        Objects.equals(this.line, templateValidationError.line) &&
        Objects.equals(this.characterPosition, templateValidationError.characterPosition);
  }

  @Override
  public int hashCode() {
    return Objects.hash(message, line, characterPosition);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TemplateValidationError {\n");
    
    sb.append("    message: ").append(toIndentedString(message)).append("\n");
    sb.append("    line: ").append(toIndentedString(line)).append("\n");
    sb.append("    characterPosition: ").append(toIndentedString(characterPosition)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

