/*
 * Postmark API
 * Postmark makes sending and receiving email incredibly easy. 
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package net.nextpulse.postmarkapp.models.server;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.math.BigDecimal;

/**
 * TemplateRecordResponse
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2017-02-24T16:43:29.220+01:00")
public class TemplateRecordResponse {
  @JsonProperty("Name")
  private String name = null;

  @JsonProperty("TemplateId")
  private BigDecimal templateId = null;

  @JsonProperty("Active")
  private Boolean active = null;

  public TemplateRecordResponse name(String name) {
    this.name = name;
    return this;
  }

   /**
   * The display name for this template.
   * @return name
  **/
  @ApiModelProperty(example = "null", value = "The display name for this template.")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public TemplateRecordResponse templateId(BigDecimal templateId) {
    this.templateId = templateId;
    return this;
  }

   /**
   * The associated ID for this template.
   * @return templateId
  **/
  @ApiModelProperty(example = "null", value = "The associated ID for this template.")
  public BigDecimal getTemplateId() {
    return templateId;
  }

  public void setTemplateId(BigDecimal templateId) {
    this.templateId = templateId;
  }

  public TemplateRecordResponse active(Boolean active) {
    this.active = active;
    return this;
  }

   /**
   * True if this template is currently available for use.
   * @return active
  **/
  @ApiModelProperty(example = "null", value = "True if this template is currently available for use.")
  public Boolean getActive() {
    return active;
  }

  public void setActive(Boolean active) {
    this.active = active;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TemplateRecordResponse templateRecordResponse = (TemplateRecordResponse) o;
    return Objects.equals(this.name, templateRecordResponse.name) &&
        Objects.equals(this.templateId, templateRecordResponse.templateId) &&
        Objects.equals(this.active, templateRecordResponse.active);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, templateId, active);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TemplateRecordResponse {\n");
    
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    templateId: ").append(toIndentedString(templateId)).append("\n");
    sb.append("    active: ").append(toIndentedString(active)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

